
-- List the number of films per category.
SELECT category.name , count(*) as number_of_films FROM film
join film_category on 
film.film_id = film_category.film_id
join category on 
film_category.category_id = category.category_id
group by category.name
order by number_of_films desc;


-- Retrieve the store ID, city, and country for each store.
SELECT st.store_id, ct.city , ctr.country FROM store as st
join address as ad on 
st.address_id = ad.address_id
join city as ct on
ad.city_id = ct.city_id
join country as ctr on
ct.country_id = ctr.country_id;

-- SELECT * FROM address;
-- SELECT * FROM city;
-- SELECT * FROM country;

-- Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
JOIN staff ON store.store_id = staff.store_id
JOIN payment ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;
SELECT * FROM staff;
SELECT * FROM store;
-- SELECT * FROM customer;
-- SELECT * FROM payment;
-- Determine the average running time of films for each category.
SELECT ct.name, ROUND(avg(fm.length)) FROM film as fm 
join film_category as fc on 
fm.film_id = fc.film_id
join category as ct on 
fc.category_id = ct.category_id
group by ct.name;
-- SELECT * FROM film_category;
-- SELECT * FROM category;


